# Generated by Django 4.2.26 on 2025-11-28 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journal', '0001_initial'),  # Need the Journal model to exist
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('submission', '0001_initial'),  # Need Article and Section models to exist as well
    ]

    operations = [
        migrations.CreateModel(
            name='FeeQuotationConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.URLField(blank=True, help_text='The URL of the third-party fee quotation API endpoint.', max_length=500)),
                ('request_body_template', models.TextField(blank=True, default='{\n    "article_id": "{{article_id}}",\n    "article_title": "{{article_title}}",\n    "author_email": "{{author_email}}",\n    "author_name": "{{author_name}}",\n    "journal_code": "{{journal_code}}",\n    "journal_name": "{{journal_name}}",\n    "section_name": "{{section_name}}",\n    "callback_url": "{{callback_url}}"\n}', help_text='JSON template for the POST request body. Available placeholders: {{article_id}}, {{article_title}}, {{author_email}}, {{author_name}}, {{journal_code}}, {{journal_name}}, {{section_name}}, {{section_id}}, {{callback_url}}')),
                ('response_quote_id_field', models.CharField(default='quote_id', help_text="The field name in the API response that contains the quote ID. Supports nested fields using dot notation (e.g., 'data.quote_id').", max_length=100)),
                ('quotation_url_template', models.CharField(blank=True, default='', help_text='URL template for the quotation page. Use {{quote_id}} as a placeholder. Example: https://billing.example.com/quote/{{quote_id}}', max_length=500)),
                ('api_headers', models.TextField(blank=True, default='{}', help_text='JSON object with additional headers to send with the API request. Example: {"Authorization": "Bearer YOUR_TOKEN"}')),
                ('webhook_secret', models.CharField(blank=True, help_text='Secret key to verify webhook callbacks from the third-party service.', max_length=128)),
                ('button_text', models.CharField(default='View Fee Quotation', help_text='Text to display on the quotation button.', max_length=100)),
                ('instructions_text', models.TextField(blank=True, default='Before submitting, please review your estimated publication fees. Click the button below to view and accept the fee quotation.', help_text='Instructions displayed to the author above the quotation button.')),
                ('is_enabled', models.BooleanField(default=False, help_text='Enable or disable the fee quotation feature for this journal.')),
                ('require_acceptance', models.BooleanField(default=True, help_text='If enabled, authors must accept the fee quotation before submitting.')),
                ('section_mode', models.CharField(choices=[('all', 'All sections'), ('include', 'Only selected sections'), ('exclude', 'All except selected sections')], default='all', help_text="Control which article sections require fee quotation. 'All sections' applies to every submission. 'Only selected sections' requires quotation only for the chosen sections. 'All except selected sections' requires quotation for all sections except the chosen ones.", max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('journal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee_quotation_config', to='journal.journal')),
                ('selected_sections', models.ManyToManyField(blank=True, help_text="Select the sections this rule applies to. The meaning depends on the 'Section mode' setting above.", related_name='fee_quotation_configs', to='submission.section')),
            ],
            options={
                'verbose_name': 'Fee Quotation Configuration',
                'verbose_name_plural': 'Fee Quotation Configurations',
            },
        ),
        migrations.CreateModel(
            name='FeeQuotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('requested', 'Requested'), ('presented', 'Presented to Author'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('error', 'Error'), ('expired', 'Expired'), ('voided', 'Voided')], default='pending', max_length=20)),
                ('external_quote_id', models.CharField(blank=True, help_text='The quote ID returned by the third-party billing service.', max_length=255, null=True)),
                ('quotation_url', models.URLField(blank=True, help_text='URL for viewing the quotation (built from template or returned by API).', max_length=1000, null=True)),
                ('api_response', models.JSONField(blank=True, help_text='The full response from the fee quotation API.', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if the quotation request failed.', null=True)),
                ('webhook_received_at', models.DateTimeField(blank=True, help_text='When the acceptance webhook was received.', null=True)),
                ('webhook_payload', models.JSONField(blank=True, help_text='The payload received from the webhook callback.', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this quotation expires.', null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_quotations', to='submission.article')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_quotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fee Quotation',
                'verbose_name_plural': 'Fee Quotations',
                'ordering': ['-created'],
            },
        ),
    ]
