# Generated by Django 4.2.26 on 2026-01-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("janeway_publication_fee_quotation_plugin", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feequotationconfiguration",
            name="request_body_template",
            field=models.TextField(
                blank=True,
                default='{\n    "article_id": "{{article_id}}",\n    "article_title": "{{article_title}}",\n    "author_email": "{{author_email}}",\n    "author_name": "{{author_name}}",\n    "authors": "{{authors}}",\n    "journal_code": "{{journal_code}}",\n    "journal_name": "{{journal_name}}",\n    "section_name": "{{section_name}}",\n    "callback_url": "{{callback_url}}"\n}',
                help_text="JSON template for the POST request body. Available placeholders: {{article_id}}, {{article_title}}, {{author_email}}, {{author_name}}, {{authors}}, {{journal_code}}, {{journal_name}}, {{section_name}}, {{section_id}}, {{callback_url}}. The {{authors}} placeholder outputs a JSON array of author objects with fields: address, authorIdentifiers, departmentName, emailAddress, firstName, lastName, middleName, institutionIdentifiers, institutionName, primary, salutation, suffix.",
            ),
        ),
    ]
